### ISSUE TITLE
Error with South migration on Postgres 8.4

### ISSUE THREAD

**Issue by jorilallo** [ojii/django-mailchimp#6]
Got the following when deploying it for Django 1.2.3, Postgres 8.4 (postgresql_psycopg2) and South 0.7.2. Works fine on my SQLite3 based development env.

<pre>
Running migrations for mailchimp:
 - Migrating forwards to 0007_extra_info.
 > mailchimp:0001_initial
 > mailchimp:0002_added_queue
 > mailchimp:0003_fixed_template_id
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/srv/project/venv/lib/python2.6/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/srv/project/venv/lib/python2.6/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/project/venv/lib/python2.6/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/project/venv/lib/python2.6/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/srv/project/venv/lib/python2.6/site-packages/south/management/commands/migrate.py", line 105, in handle
    ignore_ghosts = ignore_ghosts,
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/__init__.py", line 191, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/migrators.py", line 221, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/migrators.py", line 292, in migrate_many
    result = self.migrate(migration, database)
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/migrators.py", line 125, in migrate
    result = self.run(migration)
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/migrators.py", line 99, in run
    return self.run_migration(migration)
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/migrators.py", line 81, in run_migration
    migration_function()
  File "/srv/project/venv/lib/python2.6/site-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/srv/project/venv/lib/python2.6/site-packages/mailchimp/migrations/0003_fixed_template_id.py", line 12, in forwards
    db.alter_column('mailchimp_queue', 'template_id', self.gf('django.db.models.fields.PositiveSmallIntegerField')())
  File "/srv/project/venv/lib/python2.6/site-packages/south/db/generic.py", line 368, in alter_column
    flatten(values),
  File "/srv/project/venv/lib/python2.6/site-packages/south/db/generic.py", line 137, in execute
    cursor.execute(sql, params)
  File "/srv/project/venv/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute
    return self.cursor.execute(query, args)
django.db.utils.DatabaseError: column "template_id" cannot be cast to type smallint
</pre>

**Comment by AnthonyBriggs** [comment]
I ran into the same problem, and managed to fix it by altering migration 0002 so that it sets template_id up as an integer. Hope this helps someone who's similarly stuck.

```
--- a/mailchimp/migrations/0002_added_queue.py
+++ b/mailchimp/migrations/0002_added_queue.py
@@ -31,7 +31,7 @@ class Migration(SchemaMigration):
             ('tracking_html_clicks', self.gf('django.db.models.fields.BooleanField')(default=True, blank=True)),
             ('google_analytics', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
             ('segment_options_conditions', self.gf('django.db.models.fields.TextField')()),
-            ('template_id', self.gf('django.db.models.fields.CharField')(max_length=50)),
+            ('template_id', self.gf('django.db.models.fields.IntegerField')()),
             ('tracking_opens', self.gf('django.db.models.fields.BooleanField')(default=True, blank=True)),
         ))
         db.send_create_signal('mailchimp', ['Queue'])
```

**Comment by ubiquitousthey** [comment]
Same issue here.  I just manually changed it.

**Comment by ogirardot** [comment]
as github duely noted, i fixed it in my fork and opened a pull request.

**Comment by ojii** [comment]
This project will be maintained at https://github.com/piquadrat/django-mailchimp from now on, if this issue still exists, please report it again at the new location. Thank you
